### ISSUE TITLE
Hacktoberfest 2019 

### ISSUE THREAD

**Issue by neerajjain92** [neerajjain92/data-structures#1]
Hello everyone! 👋
My repository for data-structures for the interview preparations is open for Hacktoberfest 2019! 🎉

Add interview questions for companies that you might have faced, with at least 5 test-cases.

<h3>Steps to follow 📜</h3>
   1. Register for Hacktoberfest

  You can register from [here](https://hacktoberfest.digitalocean.com/)

2. Fork it 🍴
You can get your own fork/copy of neerajjain92/data-structures by using the Fork button.

3. Add problems that you might have faced during the interview prep of companies, add their entries in respective sections of the readme file.

4. Create a Pull Request.

Just good to have things
1) Star this repository if you feel it is helpful for your interview prep.
2) Follow Me 💯

**Comment by jjjimenez100** [comment]
I was thinking that maybe we can improve the way the project is currently structured? Categorize them instead to the type/category of problem (Arrays, Strings, etc.) instead of where the problem was found? So it'll be much easier to look in one place and check if a certain problem is already solved and present with the repo. :D
